src/Entity/Setting.php
<?php

namespace App\Entity;

use App\Repository\SettingRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SettingRepository::class)
 */
class Setting
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=5, nullable=true)
     */
    private $currencyName='USD';

    /**
     * @ORM\Column(type="string", length=5, nullable=true)
     */
    private $currencySide='left';

    /**
     * @ORM\Column(type="string", length=2, nullable=true)
     */
    private $currencyDecimal='2';

    /**
     * @ORM\Column(type="string", length=2, nullable=true)
     */
    private $currencyThousandSeparator=',';

    /**
     * @ORM\Column(type="string", length=1, nullable=true)
     */
    private $dateSeparator='-';

    /**
     * @ORM\Column(type="string", length=5, nullable=true)
     */
    private $shortDate1='Y';

    /**
     * @ORM\Column(type="string", length=5, nullable=true)
     */
    private $shortDate2='m';

    /**
     * @ORM\Column(type="string", length=5, nullable=true)
     */
    private $mediumDate1='Y';

    /**
     * @ORM\Column(type="string", length=5, nullable=true)
     */
    private $mediumDate2='m';

    /**
     * @ORM\Column(type="string", length=5, nullable=true)
     */
    private $mediumDate3='d';

    /**
     * @ORM\Column(type="string", length=5, nullable=true)
     */
    private $longDate1='Y';

    /**
     * @ORM\Column(type="string", length=5, nullable=true)
     */
    private $longDate2='m';

    /**
     * @ORM\Column(type="string", length=5, nullable=true)
     */
    private $longDate3='d';

    /**
     * @ORM\Column(type="string", length=5, nullable=true)
     */
    private $longDate4='H';

    /**
     * @ORM\Column(type="string", length=5, nullable=true)
     */
    private $longDate5='i';

    /**
     * @ORM\Column(type="integer")
     */
    private $productNew = 30;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $activationLink="http://localhost:8000/activation/getKey";

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $withSubscription = true;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $accessLimit = 24;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $timeValiditySale = 24;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $saleReceiptHeight=210;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $saleReceiptWidth=80;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $saleFontSize=16;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $saleMarginLeft=1;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $saleMarginRight=1;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $saleMarginTop=5;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $reportHeight=297;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $reportWidth=210;

    /**
     * @ORM\Column(type="integer", length=5, nullable=true)
     */
    private $reportFontSize=14;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $withExpiration=true;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $productWithImage=false;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $productWithDiscount=false;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $withBarcode=true;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $generateBarcode=false;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $withSubstitute=false;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $withBatchPrice=true;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $daysBeforeExpiration=50;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $withRawExpiration=false;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $daysBeforeRawExpiration=50;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $withPurchasePrice=true;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $withDiscount=false;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $withPartialPayment=true;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $printDirectly=true;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $withGuiSale=false;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $withSoftDelete=true;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $withWholeSale=true;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $barcodeWidth=100;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $barcodeHeight=50;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $withSettlement=false;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $withAccounting=false;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $withHrm=false;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $withExpense=true;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $withProduction=false;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $withClubPoint=false;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $maxIntervalPeriod=30;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $randomCharacter=20;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $themeId;

    /**
     * @ORM\Column(type="boolean")
     */
    private $withSaleReturn=false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $withStockReturn=false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $withPackaging=false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $withStockGenerateNumInvoice = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $withGapProduction=false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $withProductReference=false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $withUserCategory=false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $withSaleNumInvoice=false;

    /**
     * @ORM\ManyToOne(targetEntity=Store::class, inversedBy="settings")
     */
    private $store;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCurrencyName(): ?string
    {
        return $this->currencyName;
    }

    public function setCurrencyName(?string $currencyName): self
    {
        $this->currencyName = $currencyName;

        return $this;
    }

    public function getCurrencySide(): ?string
    {
        return $this->currencySide;
    }

    public function setCurrencySide(?string $currencySide): self
    {
        $this->currencySide = $currencySide;

        return $this;
    }

    public function getCurrencyDecimal(): ?string
    {
        return $this->currencyDecimal;
    }

    public function setCurrencyDecimal(?string $currencyDecimal): self
    {
        $this->currencyDecimal = $currencyDecimal;

        return $this;
    }

    public function getCurrencyThousandSeparator(): ?string
    {
        return $this->currencyThousandSeparator;
    }

    public function setCurrencyThousandSeparator(?string $currencyThousandSeparator): self
    {
        $this->currencyThousandSeparator = $currencyThousandSeparator;

        return $this;
    }

    public function getDateShort(): ?string
    {
        return $this->getShortDate1().$this->getDateSeparator()
            .$this->getShortDate2();
    }


    public function getDateMedium(): ?string
    {
        return $this->getMediumDate1()
            .$this->getDateSeparator()
            .$this->getMediumDate2()
            .$this->getDateSeparator()
            .$this->getMediumDate3();
    }

    public function getDateLong(): ?string
    {
        return $this->getLongDate1()
            .$this->getDateSeparator()
            .$this->getLongDate2()
            .$this->getDateSeparator()
            .$this->getLongDate3()
            .' '
            .$this->getLongDate4()
            .':'
            .$this->getLongDate5();
    }


    public function getDateSeparator(): ?string
    {
        return $this->dateSeparator;
    }

    public function setDateSeparator(?string $dateSeparator): self
    {
        $this->dateSeparator = $dateSeparator;

        return $this;
    }

    public function getDateMediumPicker(): ?string
    {
        return str_replace(array('Y', 'm','d'),array('yyyy', 'mm', 'dd'),$this->getDateMedium());
    }


    public function getDateLongPicker(): ?string
    {
        return str_replace(
            array('Y','m','d','H', 'i'),
            array('yyyy','mm', 'dd','hh', 'ii'),
            $this->getDateLong());
    }


    public function getLongDateJs(): ?string
    {
        return str_replace(
            array('Y','m','d','H', 'i'),
            array('YYYY','MM', 'DD','HH', 'mm'),
            $this->getDateLong());
    }

    public function getMediumDateJs(): ?string
    {
        return str_replace(
            array('Y','m','d'),
            array('YYYY','MM', 'DD'),
            $this->getDateMedium());
    }


    public function getShortDate1(): ?string
    {

src/Controller/NoticeBoardController.php
<?php


namespace App\Controller;


use App\Entity\NoticeBoard;
use App\Entity\NoticeBoardEmployee;
use App\Entity\Store;
use App\Form\NoticeBoardType;
use App\Repository\BankRepository;
use App\Repository\NoticeBoardEmployeeRepository;
use App\Repository\NoticeBoardRepository;
use App\Repository\UserRepository;
use App\Util\GlobalConstant;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class NoticeBoardController extends AbstractController
{

    /**
     * @var Store
     */
    private $store;

    /**
     * ExpenseController constructor.
     * @param RequestStack $requestStack
     */
    public function __construct(RequestStack $requestStack)
    {
        $this->store = $requestStack->getSession()->get('store');
    }

    /**
     * @Route("/noticeBoard", name="notice_board_index")
     * @param NoticeBoardRepository $noticeBoardRepository
     * @param UserRepository $userRepository
     * @return Response
     */
    public function index(NoticeBoardRepository $noticeBoardRepository,
                          UserRepository $userRepository)
    {

        $model['noticeBoards'] = $noticeBoardRepository->findBy(['store'=>$this->store]);
        $model['users'] = $userRepository->findWithRole($this->store);

        //breadcumb
        $model['entity'] = 'controller.noticeBoard.index.entity';
        $model['page'] = 'controller.noticeBoard.index.page';
        return $this->render('noticeBoard/index.html.twig', $model);
    }


    /**
     * @Route("/noticeBoard/addUser", name="notice_board_add_user")
     * @param Request $request
     * @param UserRepository $userRepository
     * @param NoticeBoardRepository $noticeBoardRepository
     * @param NoticeBoardEmployeeRepository $noticeBoardEmployeeRepository
     * @param EntityManagerInterface $entityManager
     * @return Response
     */
    public function addUser(Request $request,
                            UserRepository $userRepository,
                            NoticeBoardRepository $noticeBoardRepository,
                            NoticeBoardEmployeeRepository $noticeBoardEmployeeRepository,
                            EntityManagerInterface $entityManager): Response
    {
        $noticeBoard = $noticeBoardRepository
            ->find((int) $request->get('noticeBoard'));

        foreach ($request->get('user') as $userid){
            $user = $userRepository->find((int) $userid);
            if ($noticeBoardEmployeeRepository
                ->findOneBy(['employee' => $user,'noticeBoard' => $noticeBoard]) === null){
                $noticeBoardEmployee = new NoticeBoardEmployee();
                $noticeBoardEmployee->setNoticeBoard($noticeBoard);
                $noticeBoardEmployee->setEmployee($user);
                $entityManager->persist($noticeBoardEmployee);
                $noticeBoard->addNoticeBoardEmployee($noticeBoardEmployee);
            }
        }

        $entityManager->persist($noticeBoard);
        $entityManager->flush();

        $this->addFlash('success',"controller.noticeBoard.addUser.flash.success");

        return $this->redirectToRoute('notice_board_index');
    }

    /**
     * @Route("/noticeBoard/deleteUser/{id}", name="notice_board_delete_user")
     * @param NoticeBoardEmployee $noticeBoardEmployee
     * @param EntityManagerInterface $entityManager
     * @return Response
     */
    public function deleteUser(NoticeBoardEmployee $noticeBoardEmployee,
                            EntityManagerInterface $entityManager): Response
    {

        $entityManager->remove($noticeBoardEmployee);
        $entityManager->flush();

        $this->addFlash('success',"controller.noticeBoard.deleteUser.flash.success");

        return $this->redirectToRoute('notice_board_index');
    }

    /**
     * @Route("/noticeBoard/new", name="notice_board_new")
     * @param Request $request
     * @param EntityManagerInterface $entityManager
     * @return Response
     * @throws Exception
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {

        $noticeBoard = new NoticeBoard();
        $form = $this->createForm(NoticeBoardType::class,$noticeBoard);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            if (!GlobalConstant::compareDate($noticeBoard->getStart(), $noticeBoard->getEnd())){
                $this->addFlash('danger',"controller.noticeBoard.new.flash.danger");
            }else{
                $noticeBoard->setStore($this->store);
                $noticeBoard->setRecorder($this->getUser());
                $entityManager->persist($noticeBoard);
                $entityManager->flush();
                $this->addFlash('success',"controller.noticeBoard.new.flash.success");
            }
        }

        $model['form'] = $form->createView();
        //breadcumb
        $model['entity'] = 'controller.noticeBoard.new.entity';
        $model['page'] = 'controller.noticeBoard.new.page';
        return $this->render('noticeBoard/new.html.twig',$model);
    }


    /**
     * @Route("/noticeBoard/edit/{id}", name="notice_board_edit")
     * @param NoticeBoard $noticeBoard
     * @param Request $request
     * @param EntityManagerInterface $entityManager
     * @return Response
     * @throws Exception
     */
    public function edit(NoticeBoard $noticeBoard, Request $request, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(NoticeBoardType::class,$noticeBoard);

        if ($request->isMethod('POST')){
            $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid()){
                if (!GlobalConstant::compareDate($noticeBoard->getStart(), $noticeBoard->getEnd())){
                    $this->addFlash('danger',"controller.noticeBoard.new.flash.danger");
                }else{
                    $entityManager->persist($noticeBoard);
                    $entityManager->flush();

                    $this->addFlash('success',"controller.noticeBoard.edit.flash.success");

                    return $this->redirectToRoute('notice_board_index');
                }
            }
        }

        $model['form'] = $form->createView();
        //breadcumb
        $model['entity'] = 'controller.noticeBoard.edit.entity';
        $model['page'] = 'controller.noticeBoard.edit.page';
        return $this->render('noticeBoard/edit.html.twig',$model);
    }

    /**
     * @Route("/noticeBoard/delete/{id}", name="notice_board_delete")
     * @param NoticeBoard $noticeBoard
     * @param EntityManagerInterface $entityManager
     * @return RedirectResponse
     */
    public function delete(NoticeBoard $noticeBoard, EntityManagerInterface $entityManager): RedirectResponse
    {
        foreach ($noticeBoard->getNoticeBoardEmployees() as $noticeBoardEmployee){
            $entityManager->remove($noticeBoardEmployee);
        }
        $entityManager->remove($noticeBoard);
        $entityManager->flush();
        $this->addFlash('success',"controller.noticeBoard.delete.flash.success");
        return $this->redirectToRoute('notice_board_index');
    }


}

templates/noticeBoard/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'noticeBoard.edit.title'|trans({},'messages',app.session.get('_locale')) }}{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('dist/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css') }}">
{% endblock %}
{% block body %}
    <div class="col-md-8 offset-md-2">
        <div class="card">
            <div class="card-body">
                <h5 class="mt-0 header-title">
                    {{ 'noticeBoard.edit.block_title'|trans }}
                    <span class="triangle-border-left pull-left"></span>
                    <span class="triangle-border-right pull-right"></span>
                </h5>
                {{ form_start(form) }}
                {{ form_widget(form) }}
                <div class="form-group mt-2">
                    <button class="btn btn-uyblue">
                        <i class="fa fa-edit"></i> &nbsp; {{ 'noticeBoard.edit.btn_add'|trans }}
                    </button>
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script src="{{ asset('dist/js/dateJs.js') }}"></script>
    <script src="{{ asset('dist/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}"></script>
    <script src="{{ asset('dist/plugins/bootstrap-datepicker/js/i18n/'~app.session.get('_locale')~'.js') }}"></script>

    <script>
        $(document).ready(function () {
            const datepicker = $('.datepicker');
            datepicker.on('focus', function (e) {
                e.preventDefault();
                $(this).attr("autocomplete", "off");
            });
            const date = dayjs(new Date()).format("{{ app.session.get('setting').mediumDateJs }}");
            datepicker.datepicker({
                format: '{{ app.session.get('setting').dateMediumPicker }}',
                autoclose: true,
                startDate: date,
                calendarWeeks: true,
                clearBtn: true,
                disableTouchKeyboard: true,
                language: "{{ app.session.get('_locale') }}"
            });
        });
    </script>
{% endblock %}

templates/noticeBoard/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'noticeBoard.new.title'|trans({},'messages',app.session.get('_locale')) }}{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('dist/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css') }}">
{% endblock %}
{% block body %}
    <div class="col-md-8 offset-md-2">
        <div class="card">
            <div class="card-body">
                <h5 class="mt-0 header-title">
                    {{ 'noticeBoard.new.block_title'|trans }}
                    <span class="triangle-border-left pull-left"></span>
                    <span class="triangle-border-right pull-right"></span>
                </h5>
                {{ form_start(form) }}
                {{ form_widget(form) }}
                <div class="form-group mt-2">
                    <button class="btn btn-uyblue">
                        <i class="fa fa-save"></i> &nbsp; {{ 'noticeBoard.new.btn_add'|trans }}
                    </button>
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
<script src="{{ asset('dist/js/dateJs.js') }}"></script>
<script src="{{ asset('dist/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}"></script>
<script src="{{ asset('dist/plugins/bootstrap-datepicker/js/i18n/'~app.session.get('_locale')~'.js') }}"></script>

<script>
    $(document).ready(function () {
        const datepicker = $('.datepicker');
        datepicker.on('focus', function (e) {
            e.preventDefault();
            $(this).attr("autocomplete", "off");
        });
        const date = dayjs(new Date()).format("{{ app.session.get('setting').mediumDateJs }}");
        datepicker.datepicker({
            format: '{{ app.session.get('setting').dateMediumPicker }}',
            autoclose: true,
            startDate: date,
            calendarWeeks: true,
            clearBtn: true,
            disableTouchKeyboard: true,
            language: "{{ app.session.get('_locale') }}"
        });
    });
</script>
{% endblock %}