src/Entity/Customer.php
<?php

namespace App\Entity;

use App\Repository\CustomerRepository;
use DateTimeImmutable;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Exception;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @Vich\Uploadable()
 * @ORM\Entity(repositoryClass=CustomerRepository::class)
 */
class Customer
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255,unique=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phoneNumber;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $gender;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $other;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $addDate;

    /**
     * @ORM\OneToMany(targetEntity=Sale::class, mappedBy="customer")
     */
    private $sales;

    /**
     * @ORM\Column(type="string", length=25, nullable=true)
     */
    private $type = 'S';

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageName;

    /**
     * @Assert\Image()
     * @Vich\UploadableField(fileNameProperty="imageName",mapping="image_user")
     * @var File|null
     */
    protected $imageFile;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity=CustomerProductPrice::class, mappedBy="customer", orphanRemoval=true)
     */
    private $customerProductPrices;

    /**
     * @ORM\Column(type="boolean")
     */
    private $enabled = true;

    /**
     * @ORM\ManyToOne(targetEntity=Store::class, inversedBy="customers")
     */
    private $store;

    public function __construct()
    {
        $this->sales = new ArrayCollection();
        $this->customerProductPrices = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(?string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(?string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getOther(): ?string
    {
        return $this->other;
    }

    public function setOther(?string $other): self
    {
        $this->other = $other;

        return $this;
    }

    public function getAddDate(): ?DateTimeInterface
    {
        return $this->addDate;
    }

    public function setAddDate(?DateTimeInterface $addDate): self
    {
        $this->addDate = $addDate;

        return $this;
    }

    /**
     * @return Collection|Sale[]
     */
    public function getSales(): Collection
    {
        return $this->sales->filter(static function(Sale $sale){
            return !$sale->getDeleted();
        });
    }

    public function getSaleNotSettled(): array
    {
        return array_filter($this->getSales()->toArray(),static function(Sale $sale){
            return $sale->getAmountDebt() > 0.0;
        });
    }

    public function getPoints(): ?int
    {
        if (empty($this->getSales()->toArray()))
            return 0;

        return array_sum(array_map(static function(Sale $sale){
            return $sale->getPoints();
        },$this->getSales()->toArray()));
    }


    public function getAmountDebt(): ?float
    {
        if (empty($this->getSales()->toArray()))
            return 0;

        return array_sum(array_map(static function(Sale $sale){
            return $sale->getAmountDebt();
        },$this->getSales()->toArray()));
    }

    public function addSale(Sale $sale): self
    {
        if (!$this->sales->contains($sale)) {
            $this->sales[] = $sale;
            $sale->setCustomer($this);
        }

        return $this;
    }

    public function removeSale(Sale $sale): self
    {
        // set the owning side to null (unless already changed)
        if ($this->sales->removeElement($sale)
            && $sale->getCustomer() === $this) {
            $sale->setCustomer(null);
        }

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getInitials(): ?string
    {
        return substr($this->name,0,1);
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     * @return Customer
     * @throws Exception
     */
    public function setImageFile(?File $imageFile): self
    {
        $this->imageFile = $imageFile;
        if (null !== $imageFile){
            $this->updatedAt = new DateTimeImmutable();
        }
        return $this;
    }

    /**
     * @return Collection|CustomerProductPrice[]
     */
    public function getCustomerProductPrices(): Collection
    {
        return $this->customerProductPrices;
    }

    public function addCustomerProductPrice(CustomerProductPrice $customerProductPrice): self
    {
        if (!$this->customerProductPrices->contains($customerProductPrice)) {
            $this->customerProductPrices[] = $customerProductPrice;
            $customerProductPrice->setProduct($this);
        }

        return $this;
    }

    public function removeCustomerProductPrice(CustomerProductPrice $customerProductPrice): self
    {
        if ($this->customerProductPrices->removeElement($customerProductPrice)) {
            // set the owning side to null (unless already changed)
            if ($customerProductPrice->getProduct() === $this) {
                $customerProductPrice->setProduct(null);
            }
        }

        return $this;
    }

    public function getEnabled(): ?bool
    {
        return $this->enabled;
    }

    public function setEnabled(bool $enabled): self
    {
        $this->enabled = $enabled;

        return $this;
    }

    public function getStore(): ?Store
    {
        return $this->store;
    }

    public function setStore(?Store $store): self
    {
        $this->store = $store;

        return $this;
    }
}

src/Entity/Sale.php
<?php

namespace App\Entity;

use App\Repository\SaleRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Picqer\Barcode\BarcodeGeneratorPNG;

/**
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Entity(repositoryClass=SaleRepository::class)
 */
class Sale
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     */
    private $amount = 0.0;

    /**
     * @ORM\Column(type="float")
     */
    private $profit = 0.0;

    /**
     * @ORM\Column(type="datetime")
     */
    private $addDate;

    /**
     * @ORM\OneToMany(targetEntity=ProductSale::class, mappedBy="sale",
     *     fetch="EXTRA_LAZY")
     */
    private $productSales;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="sales",
     *     fetch="EAGER")
     * @ORM\JoinColumn(nullable=false)
     */
    private $recorder;

    /**
     * @ORM\ManyToOne(targetEntity=PaymentMethod::class, inversedBy="sales",fetch="EAGER")
     */
    private $paymentMethod;

    /**
     * @ORM\Column(type="boolean")
     */
    private $deleted = false;

    /**
     * @ORM\Column(type="float")
     */
    private $amountReceived = 0.0;

    /**
     * @ORM\ManyToOne(targetEntity=Customer::class, inversedBy="sales")
     */
    private $customer;

    /**
     * @ORM\ManyToMany(targetEntity=Tax::class)
     */
    private $taxs;

    /**
     * @ORM\Column(type="float")
     */
    private $taxAmount = 0;

    /**
     * @ORM\OneToMany(targetEntity=SalePayment::class, mappedBy="sale", orphanRemoval=true)
     */
    private $salePayments;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $reason;

    /**
     * @ORM\Column(type="string", length=25, nullable=true)
     */
    private $type;

    /**
     * @ORM\Column(type="float")
     */
    private $discount = 0.0;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isDraft = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $adjusted=false;

    /**
     * @ORM\Column(type="string", length=255, nullable=true, unique=true)
     */
    private $numInvoice;

    /**
     * @ORM\ManyToOne(targetEntity=Store::class, inversedBy="sales")
     */
    private $store;


    public function __construct()
    {
        $this->productSales = new ArrayCollection();
        $this->taxs = new ArrayCollection();
        $this->salePayments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProfit(): ?float
    {
        return $this->profit;
    }

    public function setProfit(float $profit): self
    {
        $this->profit = $profit;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function getAmountWithoutDiscount(): ?float
    {
        return $this->amount + $this->getDiscount();
    }


    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getBarCode(): ?string
    {
        if ($this->getCode() === null){
            return null;
        }
        $generator = new BarcodeGeneratorPNG();
        $barcode = $generator->getBarcode($this->getCode(), $generator::TYPE_CODE_128,
            1, 20, [0, 0, 0]);
        return base64_encode($barcode);
    }

    public function getAddDate(): ?DateTimeInterface
    {
        return $this->addDate;
    }

    public function setAddDate(DateTimeInterface $addDate): self
    {
        $this->addDate = $addDate;

        return $this;
    }

    /**
     * @return Collection|ProductSale[]
     */
    public function getProductSales(): Collection
    {
        return $this->productSales;
    }

    public function getRecorder(): ?User
    {
        return $this->recorder;
    }

    public function setRecorder(?User $recorder): self
    {
        $this->recorder = $recorder;

        return $this;
    }

    public function getPaymentMethod(): ?PaymentMethod
    {
        return $this->paymentMethod;
    }

    public function setPaymentMethod(?PaymentMethod $paymentMethod): self
    {
        $this->paymentMethod = $paymentMethod;

        return $this;
    }

    public function getDeleted(): ?bool
    {
        return $this->deleted;
    }

    public function setDeleted(bool $deleted): self
    {
        $this->deleted = $deleted;

        return $this;
    }

    public function getAmountReceived(): ?float
    {
        return $this->amountReceived;
    }

    public function getAmountTotalReceived($start=null,$end=null): ?float
    {

        return ($this->amountReceived >= $this->getAmount())?
            $this->amountReceived - $this->getAmountToRepay():
            $this->amountReceived + $this->getAmountSettled($start,$end);
    }

    public function getTaxAmount(): ?float
    {
        return $this->taxAmount;
    }

    public function getAmountWithoutTax(): ?float
    {
        return $this->getAmount() - $this->getTaxAmount();
    }

    public function getAmountToRepay(): ?float
    {
        return $this->getAmountReceived() - $this->getAmount();
    }

    public function getAmountDebt(): ?float
    {
        return $this->getAmount() - $this->getAmountTotalReceived();
    }

    public function getAmountSettled($start=null,$end=null): ?float
    {
        if (empty($this->getSalePayments()->toArray()))
            return 0;

        $salePayments = ($start!==null && $end!==null)?array_filter($this->getSalePayments()->toArray(),
            static function(SalePayment $salePayment) use ($start,$end){
                return ($salePayment->getAddDate() !== null &&
                    $salePayment->getAddDate() >= $start &&
                    $salePayment->getAddDate() <= $end);
            }): $this->getSalePayments()->toArray();

        return array_sum(array_map(static function(SalePayment $salePayment){
            return $salePayment->getAmount();
        },$salePayments));
    }

    public function getAmountProductSales(): ?float
    {
        if (empty($this->getProductSales()->toArray()))
            return 0;

        return array_sum(array_map(static function(ProductSale $productSale) {
            return $productSale->getSubtotal();
        },$this->getProductSales()->toArray()));
    }

    public function getPoints(): ?int
    {
        if (empty($this->getProductSales()->toArray()))
            return 0;

        return array_sum(array_map(static function(ProductSale $productSale) {
            return $productSale->getPoint();
        },$this->getProductSales()->toArray()));
    }

    public function getProfitProductSales(): ?float
    {
        if (empty($this->getProductSales()->toArray()))
            return 0;

        return array_sum(array_map(static function(ProductSale $productSale) {
            return $productSale->getProfit();
        },$this->getProductSales()->toArray()));
    }

    public function setAmountReceived(float $amountReceived): self
    {
        $this->amountReceived = $amountReceived;

        return $this;
    }

    public function getCode(): ?string {
        return str_pad($this->getId(),6,'0',STR_PAD_LEFT);
    }

    public function getCustomer(): ?Customer
    {
        return $this->customer;
    }

    public function setCustomer(?Customer $customer): self
    {
        $this->customer = $customer;

        return $this;
    }

    /**
     * @return Collection|Tax[]
     */
    public function getTaxs(): Collection
    {
        return $this->taxs;
    }

    public function addTax(Tax $tax): self
    {
        if (!$this->taxs->contains($tax)) {
            $this->taxs[] = $tax;
        }

        return $this;
    }

    public function removeTax(Tax $tax): self
    {
        $this->taxs->removeElement($tax);

        return $this;
    }

    public function setTaxAmount(float $taxAmount): self
    {
        $this->taxAmount = $taxAmount;

        return $this;
    }

    /**
     * @return Collection|SalePayment[]
     */
    public function getSalePayments(): Collection
    {
        return $this->salePayments;
    }




    public function addSalePayment(SalePayment $salePayment): self
    {
        if (!$this->salePayments->contains($salePayment)) {
            $this->salePayments[] = $salePayment;
            $salePayment->setSale($this);
        }

        return $this;
    }

    public function removeSalePayment(SalePayment $salePayment): self
    {
        if ($this->salePayments->removeElement($salePayment)) {
            // set the owning side to null (unless already changed)
            if ($salePayment->getSale() === $this) {
                $salePayment->setSale(null);
            }
        }

        return $this;
    }

    public function getReason(): ?string
    {
        return $this->reason;
    }

    public function setReason(?string $reason): self
    {
        $this->reason = $reason;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDiscount(): ?float
    {
        return $this->discount;
    }

    public function setDiscount(float $discount): self
    {
        $this->discount = $discount;

        return $this;
    }

    public function getIsDraft(): ?bool
    {
        return $this->isDraft;
    }

    public function setIsDraft(bool $isDraft): self
    {
        $this->isDraft = $isDraft;

        return $this;
    }

    public function getAdjusted(): ?bool
    {
        return $this->adjusted;
    }

    public function setAdjusted(bool $adjusted): self
    {
        $this->adjusted = $adjusted;

        return $this;
    }

templates/customer/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'customer.edit.title'|trans({},'messages',app.session.get('_locale')) }}{% endblock %}

{% block body %}
    <div class="col-md-8 offset-md-2">
        <div class="card">
            <div class="card-body">
                <h5 class="mt-0 header-title">
                    {{ 'customer.edit.block_title'|trans }}
                    <span class="triangle-border-left pull-left"></span>
                    <span class="triangle-border-right pull-right"></span>
                </h5>
                {{ form_start(form) }}
                {{ form_widget(form) }}
                <div class="form-group mt-2">
                    <button class="btn btn-uyblue">
                        <i class="fa fa-edit"></i> &nbsp; {{ 'customer.edit.btn_add'|trans }}
                    </button>
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/customer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'customer.index.title'|trans({},'messages',app.session.get('_locale')) }}{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('dist/plugins/datatables/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('dist/plugins/datatables/buttons.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('dist/plugins/datatables/responsive.bootstrap4.min.css') }}">
{% endblock %}

{% block javascripts %}
    {%  include 'partials/jsTable.html.twig' %}
    <script src="{{ asset('dist/js/datatable/sb-datatables-'~app.session.get('_locale')~'.js') }}"></script>

    <script type="text/javascript">
        getDataTable($('#dataTable'));

        $('#dataTable tbody').on( 'click', 'tr', function () {
            $(this).toggleClass('selected bg-light');
        } );

        const body = $('body');
        body.on('click', '.detail-saleDebt', function (e) {
            e.preventDefault();
            const customerId = $(this).attr('data-customer');
            const link = '{{ path('rest_customer_saleDebt_modal') }}';
            modalSaleDebt(customerId,link);

        });

        function modalSaleDebt(customerId,link) {
            let data = new FormData();
            data.append("id", customerId + '');

            $('#saleDebtmodal').html("");
            fetch(link, {
                method: 'POST',
                credentials: 'include',
                body: data,
            }).then(async response => {
                try {
                    const data = await response.json();
                    $('#saleDebtmodal').html(data.content);
                    getDataTable($('#dataTable2'));
                    $('.saleDebtmodal').modal('show');
                    return false;
                } catch (reason) {
                    console.log(reason);
                }
            }).catch(function (reason) {
                console.log(reason);
            })
        }
    </script>
{% endblock %}
{% block body %}
    <div class="card">
        <div class="card-body">
            <h5 class="mt-0 header-title">
                {{ 'customer.index.block_title'|trans }}
                ({{ customers|length|formatedInt }})
                <span class="triangle-border-left pull-left"></span>
                <span class="triangle-border-right pull-right ml-3"></span>
                {% if is_granted(permission_verify,'CUSTOMER_NEW') %}
                    <span class="pull-right">
                        <a class="btn btn-outline-uyblue" href="{{ path('customer_new') }}">
                            <i class="fa fa-plus"></i>
                        </a>
                    </span>
                {% endif %}
            </h5>
            <div class="table-responsive">
                <table class="table" style="width: 100%;" id="dataTable">
                <thead>
                <tr>
                    <th>{{ 'customer.index.tr_name'|trans }}</th>
                    <th class="not-sort">{{ 'customer.index.tr_tel'|trans }}</th>
                    <th class="not-sort">{{ 'customer.index.tr_email'|trans }}</th>
                    <th>{{ 'customer.index.tr_gender'|trans }}</th>
                    <th>{{ 'customer.index.tr_type'|trans }}</th>
                    <th>{{ 'customer.index.tr_amountDebt'|trans }}</th>
                    {#<th>{{ 'customer.index.tr_bloodGroup'|trans }}</th>#}
                    <th class="not-export not-sort">{{ 'customer.index.tr_actions'|trans }}</th>
                </tr>
                </thead>
                <tbody>
                {% for customer in customers %}
                    <tr>
                        <td class="text-capitalize">
                            <a href="{{ path('performance_customer',{id: customer.id}) }}">
                                {{ customer.name }}
                            </a>
                        </td>
                        <td>{{ customer.phoneNumber }}</td>
                        <td>
                            {% if customer.email %}
                                {{ customer.email }}
                            {% else %}
                                //
                            {% endif %}
                        </td>
                        {#<td>
                            {% if customer.bloodGroup %}
                                {{ customer.bloodGroup }}
                            {% else %}
                                //
                            {% endif %}

                        </td>#}
                        <td>{{ customer.gender|trans }}</td>
                        <td>
                            <span class="badge badge-info p-2">
                                {{ customer.type }}
                            </span>
                        </td>
                        <td >
                            <a class="detail-saleDebt"
                               href="#salesDebtModal{{customer.id}}"
                               data-customer="{{ customer.id }}">
                                {{ 'customer.index.tr_seeMore'|trans }}
                            </a>
                        </td>
                        <td>
                            {% if is_granted(permission_verify,'CUSTOMER_EDIT') %}
                            <a href="{{ path('customer_edit',{'id': customer.id}) }}" class="p-2 badge badge-uyblue">
                                <i class="fa fa-pencil"></i>
                            </a>
                            {% endif %}
                            {% if is_granted(permission_verify,'CUSTOMER_DELETE') %}
                            <a href="#deleteModal{{customer.id}}" data-toggle="modal" class="p-2 badge badge-danger ">
                                <i class="fa fa-remove"></i>
                            </a>
                            <!-- Delete Modal -->
                            <div class="modal fade" id="deleteModal{{customer.id}}" tabindex="-1" role="dialog"
                                 aria-labelledby="deleteModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">{{ 'customer.index.modal.title'|trans }}</h5>
                                            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">×</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            {{ 'customer.index.modal.body'|trans }}
                                            <span class="text-info">{{ customer.name }}</span>?
                                        </div>
                                        <div class="modal-footer">
                                            <button class="btn btn-secondary" type="button" data-dismiss="modal">
                                                {{ 'cancel'|trans }}
                                            </button>
                                            <a class="btn btn-danger" href="{{path('customer_delete',{'id':customer.id})}}">
                                                <i class="fa fa-trash"></i> {{ 'delete'|trans }}
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            </div>
        </div>
    </div>
    <!-- sale debt Modal -->
    <div id="saleDebtmodal"></div>
{% endblock %}

templates/customer/modalSaleDebt.html.twig
<!-- Delete Modal -->
<div class="modal fade saleDebtmodal" id="salesDebtModal{{customer.id}}"
     tabindex="-1" role="dialog"
     aria-labelledby="salesDebtModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">
                    {{ 'customer.index.salesModal.title'|trans({},'messages',app.session.get('_locale')) }}
                </h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="table-responsive">
                <table class="table table-striped" style="width: 100%;" id="dataTable2">
                    <thead class="font-weight-bold">
                    <th class="not-sort">
                        {{ 'customer.index.salesModal.tr_sale'|trans({},'messages',app.session.get('_locale')) }}
                    </th>
                    <th class="not-sort">
                        {{ 'customer.index.salesModal.tr_date'|trans({},'messages',app.session.get('_locale')) }}
                    </th>
                    <th>
                        {{ 'customer.index.salesModal.tr_paymentMethod'|trans({},'messages',app.session.get('_locale')) }}
                    </th>
                    <th>
                        {{ 'customer.index.salesModal.tr_amount_toPay'|trans({},'messages',app.session.get('_locale')) }}
                    </th>
                    </thead>
                    <tbody>
                    {% for sale in customer.saleNotSettled %}
                        <tr>
                            <td>
                                <a href="{{ path('sale_detail',{id:sale.id}) }}">
                                    {{ sale.code }}
                                </a>
                            </td>
                            <td>{{ sale.addDate|longDate }}</td>
                            <td>
                                {% if sale.paymentMethod %}
                                    {{ sale.paymentMethod.name }}
                                {% else %}
                                    /
                                {% endif %}
                            </td>
                            <td>{{ sale.amountDebt|formated }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    {% if customer.amountDebt > 0 %}
                        <tfoot>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>
                                <span class="font-weight-bold text-info">
                                    {{ customer.amountDebt|customCurrency }}
                                </span>
                            </td>
                        </tr>
                        </tfoot>
                    {% endif %}
                </table>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">
                    {{ 'cancel'|trans({},'messages',app.session.get('_locale')) }}
                </button>
            </div>
        </div>
    </div>
</div>

templates/customer/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'customer.new.title'|trans({},'messages',app.session.get('_locale')) }}{% endblock %}

{% block body %}
    <div class="col-md-8 offset-md-2">
        <div class="card">
            <div class="card-body">
                <h5 class="mt-0 header-title">
                    {{ 'customer.new.block_title'|trans }}
                    <span class="triangle-border-left pull-left"></span>
                    <span class="triangle-border-right pull-right"></span>
                </h5>
                {{ form_start(form) }}
                {{ form_widget(form) }}
                <div class="form-group mt-2">
                    <button class="btn btn-uyblue">
                        <i class="fa fa-save"></i> &nbsp; {{ 'customer.new.btn_add'|trans }}
                    </button>
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}