src/Entity/Loss.php
<?php

namespace App\Entity;

use App\Repository\LossRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=LossRepository::class)
 */
class Loss
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive()
     */
    private $qty=1;

    /**
     * @ORM\Column(type="datetime")
     */
    private $addDate;

    /**
     * @ORM\ManyToOne(targetEntity=LossType::class, inversedBy="losses",
     *     fetch="EAGER")
     */
    private $type;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="losses",
     *     fetch="EAGER")
     * @ORM\JoinColumn(nullable=false)
     */
    private $recorder;

    /**
     * @ORM\ManyToOne(targetEntity=ProductStock::class, inversedBy="losses",
     *     fetch="EAGER")
     * @ORM\JoinColumn(nullable=true)
     */
    private $productStock;

    /**
     * @ORM\ManyToOne(targetEntity=Store::class, inversedBy="losses")
     */
    private $store;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQty(): ?int
    {
        return $this->qty;
    }

    public function setQty(int $qty): self
    {
        $this->qty = $qty;

        return $this;
    }

    public function getAddDate(): ?DateTimeInterface
    {
        return $this->addDate;
    }

    public function setAddDate(DateTimeInterface $addDate): self
    {
        $this->addDate = $addDate;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->getProductStock()->getProduct();
    }

    public function getType(): ?LossType
    {
        return $this->type;
    }

    public function setType(?LossType $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getRecorder(): ?User
    {
        return $this->recorder;
    }

    public function setRecorder(?User $recorder): self
    {
        $this->recorder = $recorder;

        return $this;
    }

    public function getProductStock(): ?ProductStock
    {
        return $this->productStock;
    }

    public function setProductStock(?ProductStock $productStock): self
    {
        $this->productStock = $productStock;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->getQty() * $this->getProductStock()->getUnitPrice();
    }

    public function getStore(): ?Store
    {
        return $this->store;
    }

    public function setStore(?Store $store): self
    {
        $this->store = $store;

        return $this;
    }
}

src/Entity/Sale.php
<?php

namespace App\Entity;

use App\Repository\SaleRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Picqer\Barcode\BarcodeGeneratorPNG;

/**
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Entity(repositoryClass=SaleRepository::class)
 */
class Sale
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     */
    private $amount = 0.0;

    /**
     * @ORM\Column(type="float")
     */
    private $profit = 0.0;

    /**
     * @ORM\Column(type="datetime")
     */
    private $addDate;

    /**
     * @ORM\OneToMany(targetEntity=ProductSale::class, mappedBy="sale",
     *     fetch="EXTRA_LAZY")
     */
    private $productSales;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="sales",
     *     fetch="EAGER")
     * @ORM\JoinColumn(nullable=false)
     */
    private $recorder;

    /**
     * @ORM\ManyToOne(targetEntity=PaymentMethod::class, inversedBy="sales",fetch="EAGER")
     */
    private $paymentMethod;

    /**
     * @ORM\Column(type="boolean")
     */
    private $deleted = false;

    /**
     * @ORM\Column(type="float")
     */
    private $amountReceived = 0.0;

    /**
     * @ORM\ManyToOne(targetEntity=Customer::class, inversedBy="sales")
     */
    private $customer;

    /**
     * @ORM\ManyToMany(targetEntity=Tax::class)
     */
    private $taxs;

    /**
     * @ORM\Column(type="float")
     */
    private $taxAmount = 0;

    /**
     * @ORM\OneToMany(targetEntity=SalePayment::class, mappedBy="sale", orphanRemoval=true)
     */
    private $salePayments;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $reason;

    /**
     * @ORM\Column(type="string", length=25, nullable=true)
     */
    private $type;

    /**
     * @ORM\Column(type="float")
     */
    private $discount = 0.0;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isDraft = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $adjusted=false;

    /**
     * @ORM\Column(type="string", length=255, nullable=true, unique=true)
     */
    private $numInvoice;

    /**
     * @ORM\ManyToOne(targetEntity=Store::class, inversedBy="sales")
     */
    private $store;


    public function __construct()
    {
        $this->productSales = new ArrayCollection();
        $this->taxs = new ArrayCollection();
        $this->salePayments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProfit(): ?float
    {
        return $this->profit;
    }

    public function setProfit(float $profit): self
    {
        $this->profit = $profit;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function getAmountWithoutDiscount(): ?float
    {
        return $this->amount + $this->getDiscount();
    }


    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getBarCode(): ?string
    {
        if ($this->getCode() === null){
            return null;
        }
        $generator = new BarcodeGeneratorPNG();
        $barcode = $generator->getBarcode($this->getCode(), $generator::TYPE_CODE_128,
            1, 20, [0, 0, 0]);
        return base64_encode($barcode);
    }

    public function getAddDate(): ?DateTimeInterface
    {
        return $this->addDate;
    }

    public function setAddDate(DateTimeInterface $addDate): self
    {
        $this->addDate = $addDate;

        return $this;
    }

    /**
     * @return Collection|ProductSale[]
     */
    public function getProductSales(): Collection
    {
        return $this->productSales;
    }

    public function getRecorder(): ?User
    {
        return $this->recorder;
    }

    public function setRecorder(?User $recorder): self
    {
        $this->recorder = $recorder;

        return $this;
    }

    public function getPaymentMethod(): ?PaymentMethod
    {
        return $this->paymentMethod;
    }

    public function setPaymentMethod(?PaymentMethod $paymentMethod): self
    {
        $this->paymentMethod = $paymentMethod;

        return $this;
    }

    public function getDeleted(): ?bool
    {
        return $this->deleted;
    }

    public function setDeleted(bool $deleted): self
    {
        $this->deleted = $deleted;

        return $this;
    }

    public function getAmountReceived(): ?float
    {
        return $this->amountReceived;
    }

    public function getAmountTotalReceived($start=null,$end=null): ?float
    {

        return ($this->amountReceived >= $this->getAmount())?
            $this->amountReceived - $this->getAmountToRepay():
            $this->amountReceived + $this->getAmountSettled($start,$end);
    }

    public function getTaxAmount(): ?float
    {
        return $this->taxAmount;
    }

    public function getAmountWithoutTax(): ?float
    {
        return $this->getAmount() - $this->getTaxAmount();
    }

    public function getAmountToRepay(): ?float
    {
        return $this->getAmountReceived() - $this->getAmount();
    }

    public function getAmountDebt(): ?float
    {
        return $this->getAmount() - $this->getAmountTotalReceived();
    }

    public function getAmountSettled($start=null,$end=null): ?float
    {
        if (empty($this->getSalePayments()->toArray()))
            return 0;

        $salePayments = ($start!==null && $end!==null)?array_filter($this->getSalePayments()->toArray(),
            static function(SalePayment $salePayment) use ($start,$end){
                return ($salePayment->getAddDate() !== null &&
                    $salePayment->getAddDate() >= $start &&
                    $salePayment->getAddDate() <= $end);
            }): $this->getSalePayments()->toArray();

        return array_sum(array_map(static function(SalePayment $salePayment){
            return $salePayment->getAmount();
        },$salePayments));
    }

    public function getAmountProductSales(): ?float
    {
        if (empty($this->getProductSales()->toArray()))
            return 0;

        return array_sum(array_map(static function(ProductSale $productSale) {
            return $productSale->getSubtotal();
        },$this->getProductSales()->toArray()));
    }

    public function getPoints(): ?int
    {
        if (empty($this->getProductSales()->toArray()))
            return 0;

        return array_sum(array_map(static function(ProductSale $productSale) {
            return $productSale->getPoint();
        },$this->getProductSales()->toArray()));
    }

    public function getProfitProductSales(): ?float
    {
        if (empty($this->getProductSales()->toArray()))
            return 0;

        return array_sum(array_map(static function(ProductSale $productSale) {
            return $productSale->getProfit();
        },$this->getProductSales()->toArray()));
    }

    public function setAmountReceived(float $amountReceived): self
    {
        $this->amountReceived = $amountReceived;

        return $this;
    }

    public function getCode(): ?string {
        return str_pad($this->getId(),6,'0',STR_PAD_LEFT);
    }

    public function getCustomer(): ?Customer
    {
        return $this->customer;
    }

    public function setCustomer(?Customer $customer): self
    {
        $this->customer = $customer;

        return $this;
    }

    /**
     * @return Collection|Tax[]
     */
    public function getTaxs(): Collection
    {
        return $this->taxs;
    }

    public function addTax(Tax $tax): self
    {
        if (!$this->taxs->contains($tax)) {
            $this->taxs[] = $tax;
        }

        return $this;
    }

    public function removeTax(Tax $tax): self
    {
        $this->taxs->removeElement($tax);

        return $this;
    }

    public function setTaxAmount(float $taxAmount): self
    {
        $this->taxAmount = $taxAmount;

        return $this;
    }

    /**
     * @return Collection|SalePayment[]
     */
    public function getSalePayments(): Collection
    {
        return $this->salePayments;
    }




    public function addSalePayment(SalePayment $salePayment): self
    {
        if (!$this->salePayments->contains($salePayment)) {
            $this->salePayments[] = $salePayment;
            $salePayment->setSale($this);
        }

        return $this;
    }

    public function removeSalePayment(SalePayment $salePayment): self
    {
        if ($this->salePayments->removeElement($salePayment)) {
            // set the owning side to null (unless already changed)
            if ($salePayment->getSale() === $this) {
                $salePayment->setSale(null);
            }
        }

        return $this;
    }

    public function getReason(): ?string
    {
        return $this->reason;
    }

    public function setReason(?string $reason): self
    {
        $this->reason = $reason;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDiscount(): ?float
    {
        return $this->discount;
    }

    public function setDiscount(float $discount): self
    {
        $this->discount = $discount;

        return $this;
    }

    public function getIsDraft(): ?bool
    {
        return $this->isDraft;
    }

    public function setIsDraft(bool $isDraft): self
    {
        $this->isDraft = $isDraft;

        return $this;
    }

    public function getAdjusted(): ?bool
    {
        return $this->adjusted;
    }

    public function setAdjusted(bool $adjusted): self
    {
        $this->adjusted = $adjusted;

        return $this;
    }

templates/pdf/adjustment.html.twig
<!DOCTYPE html>
<html>
<head>
    <title>{{ 'pdf.adjustment.title'|trans({},'messages',app.session.get('_locale')) }}</title>
    <style type="text/css" rel="stylesheet" media="all">
        {% include 'pdf/css.html.twig' %}
    </style>
</head>
<body>
{% set setting = app.session.get('setting') %}
<div class="container-fluid" style="font-size: {{ setting.reportFontSize }}">
    <div class="row" style="margin-bottom: 40px">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-4 text-center">
            {% if store.imageName is not null %}
                <img id="logo" class="rounded img-responsive center-block"
                     src="{{ storeImage }}{{ store.imageName }}"
                     alt="{{store.name}}" style="height: 200px">
            {% else %}
                <img id="logo" class="rounded" src="{{ appLogo }}"
                     alt="" style="height: 200px">
            {% endif %}
        </div>
    </div>
    <div class="row">
        {% if store is not null %}
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
            <table class="table table-bordered text-center">
                <tr class="font-weight-bold">
                    <td>{{ store.name }}</td>
                </tr>
                {% if store.email is not empty %}
                <tr>
                    <td>{{ store.email }}</td>
                </tr>
                {% endif %}
                {% if store.phoneNumber is not empty %}
                <tr>
                    <td>{{ store.phoneNumber }}</td>
                </tr>
                {% endif %}
            </table>
        </div>
        {% endif %}
    </div>
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12 col-xs-12">
            <table class="table table-bordered table-striped">
                <tr>
                    <td class="h2 text-center"
                        colspan="4">
                        {{ 'pdf.adjustment.tr_title'|trans({},'messages',app.session.get('_locale')) }}
                        ({{ adjustment.productAdjusts|length|formatedInt }})
                    </td>
                </tr>
                <tr class="font-weight-bold">
                    <td>{{ 'pdf.adjustment.tr_product'|trans({},'messages',app.session.get('_locale')) }}</td>
                    <td>{{ 'pdf.adjustment.tr_qtyExpected'|trans({},'messages',app.session.get('_locale')) }}</td>
                    <td>{{ 'pdf.adjustment.tr_newQty'|trans({},'messages',app.session.get('_locale')) }}</td>
                    <td>{{ 'pdf.adjustment.tr_difference'|trans({},'messages',app.session.get('_locale')) }}</td>
                </tr>
                {% for productAdjust in adjustment.productAdjusts %}
                    <tr>
                        <td>{{ productAdjust.product.name }}</td>
                        <td>{{ productAdjust.qtyBeforeAdjust|formatedInt }}</td>
                        <td>{{ productAdjust.newQty|formatedInt }}</td>
                        <td>{{ productAdjust.qty|formatedInt }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
</body>
</html>

templates/pdf/invoice.html.twig
<!DOCTYPE html>
<html>
<head>
    <title>{{ 'pdf.invoice.title'|trans({},'messages',app.session.get('_locale')) }}</title>
    <style type="text/css" rel="stylesheet" media="all">
        {% include 'pdf/css.html.twig' %}
    </style>
</head>
<body>
{% set setting = app.session.get('setting') %}
<div class="container-fluid" style="font-size: {{ setting.reportFontSize }}">
    <div class="row" style="margin-bottom: 40px">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 border-dark py-2
        rounded text-center">
            {% if store.imageName is not null %}
                <img id="logo" class="rounded img-responsive center-block"
                     src="{{ storeImage }}{{ store.imageName }}"
                     alt="{{store.name}}" style="height: 100px">
            {% else %}
                <img id="logo" class="rounded" src="{{ appLogo }}"
                     alt="" style="height: 100px">
            {% endif %}<br>
            <b>{{ store.name }}</b><br>
            {% if store.phoneNumber is not empty %}
                {{ 'report.phone'|trans({},'messages',app.session.get('_locale')) }}: {{ store.phoneNumber }}
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
            <p>
                <b class="text-uppercase">{{ sale.customer.name }}</b><br>
                {{ sale.customer.email }}<br>
                {% if sale.customer.phoneNumber is not null %}
                    {{ sale.customer.phoneNumber }}
                {% endif %}
            </p>
        </div>

        <div class="col-sm-6 col-md-6 col-lg-6 col-xs-6
        col-sm-offset-2 col-md-offset-2 col-lg-offset-2 col-xs-offset-2">
            <table class="table table-borderless">
                <tr>
                    <td class="text-right font-weight-bold">
                        {{ 'pdf.invoice.tr_code'|trans({},'messages',app.session.get('_locale')) }}:
                    </td>
                    <td>{{ sale.code }}</td>
                </tr>
                {% if sale.numInvoice %}
                    <tr>
                        <td class="text-right font-weight-bold">
                            {{ 'pdf.invoice.tr_numInvoice'|trans({},'messages',app.session.get('_locale')) }}:
                        </td>
                        <td>{{ sale.numInvoice }}</td>
                    </tr>
                {% endif %}
                <tr>
                    <td class="text-right font-weight-bold">
                        {{ 'pdf.invoice.tr_date'|trans({},'messages',app.session.get('_locale')) }}:
                    </td>
                    <td>{{ sale.addDate|longDate }}</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12 col-xs-12">
            <table class="table table-bordered table-striped">
                <tr class="font-weight-bold">
                    <td>{{ 'pdf.invoice.tr_designation'|trans({},'messages',app.session.get('_locale')) }}</td>
                    <td>{{ 'pdf.invoice.tr_unitPrice'|trans({},'messages',app.session.get('_locale')) }}</td>
                    <td>{{ 'pdf.invoice.tr_qty'|trans({},'messages',app.session.get('_locale')) }}</td>
                    <td>{{ 'pdf.invoice.tr_amount'|trans({},'messages',app.session.get('_locale')) }}</td>
                </tr>
                {% for productSale in sale.productSales %}
                    <tr>
                        <td>{{ productSale.product.name }}</td>
                        <td>{{ productSale.unitPrice|formated }}</td>
                        <td>{{ productSale.qty|formatedInt }}</td>
                        <td>{{ productSale.subtotal|formated }}</td>
                    </tr>
                {% endfor %}
                <tr>
                    <td></td>
                    <td></td>
                    <td class="font-weight-bold">{{ 'pdf.invoice.tr_subtotal'|trans({},'messages',app.session.get('_locale')) }}</td>
                    <td>
                        {{sale.amountWithoutTax|formated}}
                    </td>
                </tr>
                {% for tax in sale.taxs %}
                    <tr>
                        <td></td>
                        <td></td>
                        <td class="font-weight-bold">{{ tax.name }}({{ tax.rate }}%)</td>
                        <td>{{ ((sale.amountWithoutTax * tax.rate)/100)|formated }}</td>
                    </tr>
                {% endfor %}
                <tr>
                    <td></td>
                    <td></td>
                    <td class="font-weight-bold">{{ 'pdf.invoice.tr_total'|trans({},'messages',app.session.get('_locale')) }}</td>
                    <td>
                        {{sale.amount|customCurrency}}
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div class="row" style="margin-top: 40px">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center h4">
            {{ store.slogan }}
        </div>
    </div>
</div>
</body>
</html>

templates/pdf/order.html.twig
<!DOCTYPE html>
<html>
<head>
    <title>{{ 'pdf.order.title'|trans({},'messages',app.session.get('_locale')) }}</title>
    <style type="text/css" rel="stylesheet" media="all">
        {% include 'pdf/css.html.twig' %}
    </style>
</head>
<body>
{% set setting = app.session.get('setting') %}
<div class="container-fluid" style="font-size: {{ setting.reportFontSize }}">
    <div class="row" style="margin-bottom: 40px">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-4 text-center">
            {% if store.imageName is not null %}
                <img id="logo" class="rounded img-responsive center-block"
                     src="{{ storeImage }}{{ store.imageName }}"
                     alt="{{store.name}}" style="height: 200px">
            {% else %}
                <img id="logo" class="rounded" src="{{ appLogo }}"
                     alt="" style="height: 200px">
            {% endif %}
        </div>
    </div>
    <div class="row">
        {% if store is not null %}
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
            <table class="table table-bordered text-center">
                <tr class="font-weight-bold">
                    <td>{{ store.name }}</td>
                </tr>
                {% if store.email is not empty %}
                <tr>
                    <td>{{ store.email }}</td>
                </tr>
                {% endif %}
                {% if store.phoneNumber is not empty %}
                <tr>
                    <td>{{ store.phoneNumber }}</td>
                </tr>
                {% endif %}
            </table>
        </div>
        {% endif %}
        {% if stock.supplier is not null %}
            <div class="col-sm-4 col-md-4 col-lg-4 col-xs-4
            col-sm-offset-4 col-md-offset-4 col-lg-offset-4 col-xs-offset-4">
                <table class="table table-bordered text-center">
                    <tr class="font-weight-bold">
                        <td>{{ stock.supplier.name }}</td>
                    </tr>
                    {% if stock.supplier.email is not empty %}
                    <tr>
                        <td>{{ stock.supplier.email }}</td>
                    </tr>
                    {% endif %}
                </table>
            </div>
        {% endif %}
    </div>
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12 col-xs-12">
            <table class="table table-bordered table-striped">
                <tr>
                    <td class="h2 text-center"
                        colspan="{% if stock.status %}4{% else %}2{% endif %}">
                        {{ 'pdf.order.tr_title'|trans({},'messages',app.session.get('_locale')) }}
                        ({{ stock.productStocks|length|formatedInt }})
                    </td>
                </tr>
                <tr class="font-weight-bold">
                    <td>{{ 'pdf.order.tr_product'|trans({},'messages',app.session.get('_locale')) }}</td>
                    {% if stock.status and setting.withPurchasePrice  %}
                        <td>{{ 'pdf.order.tr_unitPrice'|trans({},'messages',app.session.get('_locale')) }}</td>
                    {% endif %}
                    <td>{{ 'pdf.order.tr_qty'|trans({},'messages',app.session.get('_locale')) }}</td>
                    {% if stock.status and setting.withPurchasePrice  %}
                        <td>{{ 'pdf.order.tr_total'|trans({},'messages',app.session.get('_locale')) }}</td>
                    {% endif %}
                </tr>
                {% set totalAmount = 0 %}
                {% for productStock in stock.productStocks %}
                    <tr>
                        <td>{{ productStock.product.name }}</td>
                        {% if stock.status and setting.withPurchasePrice  %}
                            <td>{{ productStock.unitPrice|formated }}</td>
                        {% endif %}
                        <td>{{ productStock.qty|formatedInt }}</td>
                        {% if stock.status and setting.withPurchasePrice  %}
                            <td>{{ productStock.subtotal|formated }}</td>
                        {% endif %}
                    </tr>
                    {% set totalAmount = totalAmount + productStock.subtotal %}
                {% endfor %}
                {% if stock.status and setting.withPurchasePrice  %}
                <tr class="font-weight-bold">
                    <td></td>
                    <td></td>
                    <td></td>
                    <td class="h6">
                        {{totalAmount|customCurrency}}
                    </td>
                </tr>
                {% endif %}
            </table>
        </div>
    </div>
</div>
</body>
</html>

templates/pdf/sale.html.twig
<!DOCTYPE html>
<html>
<head>
    <title>{{ 'pdf.sale.title'|trans({},'messages',app.session.get('_locale')) }}</title>
    <style type="text/css" rel="stylesheet" media="all">
        {% include 'pdf/css.html.twig' %}
    </style>
    <script type="module">
        try {
            this.print();
        } catch (e) {
            window.onload = window.print;
        }
    </script>
</head>
{% set setting = app.session.get('setting') %}
<body style="font-size: '{{ setting.saleFontSize }}pt';">
{#<body style="@font-face {
        font-family: 'f25';
        src: url('{{ asset('dist/fonts/F25_Bank_Printer.otf') }}') format('otf'),
        url('{{ asset('dist/fonts/F25_Bank_Printer.ttf') }}') format('ttf');};
        font-size: '{{ setting.saleFontSize }}pt'; font-family: 'f25', sans-serif;">#}
<div style="width: 100% !important;">
    <div class="row mb-4" style="margin-bottom: 40px;">
        {% if store is not null %}
            <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12 text-center">
                <b>{{ store.name }}</b><br>
                {% if store.address is not empty %}
                    {{ store.address }}<br>
                {% endif %}
                {% if store.phoneNumber is not empty %}
                    Tel: {{ store.phoneNumber }}<br>
                {% endif %}
                {% if store.email is not empty %}
                    Email: {{ store.email }}<br>
                {% endif %}
                {% if store.webSite is not empty %}
                    web: {{ store.webSite }}<br>
                {% endif %}
            </div>
        {% endif %}
    </div>
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12 col-xs-12">
            <table class="table">
                <tr>
                    <td colspan="3" class="text-center">
                        <span>
                            {{ 'pdf.sale.tr_sale'|trans({},'messages',app.session.get('_locale')) }}
                            {{ sale.code }}
                        </span>
                    </td>
                </tr>
                <tr style="font-weight: bold">
                    <td style="width: 35%">{{ 'pdf.sale.tr_product'|trans({},'messages',app.session.get('_locale')) }}</td>
                    <td style="width: 30%">
                        {{ 'pdf.sale.tr_qty_price'|trans({},'messages',app.session.get('_locale')) }}
                    </td>
                    <td style="width: 35%">
                        {{ 'pdf.sale.tr_cost'|trans({},'messages',app.session.get('_locale')) }}
                    </td>
                </tr>
                {% for productSale in sale.productSales %}
                    <tr>
                        <td>{{ productSale.product.name }}</td>
                        <td>
                            {{ productSale.product.sellPrice|formated }}
                            ({{ productSale.qty|formatedInt }})
                        </td>
                        <td>{{ productSale.subtotal|formated }}</td>
                    </tr>
                {% endfor %}
                {% for tax in sale.taxs %}
                    <tr>
                        <td colspan="2">{{ tax.name }} ({{ tax.rate }}%)</td>
                        <td>
                            {{(tax.rate * sale.amountWithoutTax/100)|round|formated}}
                        </td>
                    </tr>
                {% endfor %}
                <tr>
                    <td colspan="2">
                        {{ 'pdf.sale.tr_amount'|trans({},'messages',app.session.get('_locale')) }}
                    </td>
                    <td style="font-weight: bold">
                        {{sale.amount|formated }}
                    </td>
                </tr>
                <tr>
                    <td colspan="3" class="text-center">
                        <span>
                            {{ 'pdf.sale.tr_amountReceived'|trans({},'messages',app.session.get('_locale')) }}:
                            <span>
                                {{sale.amountReceived|formated }}
                            </span>
                        </span>
                        <br>
                        {% if sale.amountToRepay >= 0 %}
                            <span>
                                {{ 'pdf.sale.tr_repay'|trans({},'messages',app.session.get('_locale')) }}:
                                {{sale.amountToRepay|formated }}
                            </span>
                        {% endif %}
                        {% if sale.amountDebt > 0 %}
                        <span>
                            {{ 'pdf.sale.tr_rest'|trans({},'messages',app.session.get('_locale')) }}:
                            {{sale.amountDebt|formated }}
                        </span>
                        {% endif %}
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div class="row" style="margin-bottom: 20px; margin-top: 20px">
        <div class="col-sm-12 col-md-12 col-lg-12 col-xs-12 text-center">
            <img style="width: 120px; height: 25px;" src="data:image/png;base64,{{ sale.barCode }}">
        </div>
    </div>
    <div class="mb-5" style="margin-bottom: 50px;">
        {{ 'pdf.sale.footer2'|trans({},'messages',app.session.get('_locale')) }} {{ 'now'|longDate }}
    </div>
    {% if store.slogan is not empty %}
        <div class="text-center text-uppercase">
            {{ store.slogan }}
        </div>
    {% endif %}

</div>
</body>
</html>