src/Entity/Bank.php
<?php

namespace App\Entity;

use App\Repository\BankRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BankRepository::class)
 */
class Bank
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $accountName;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     */
    private $accountNumber;

    /**
     * @ORM\OneToMany(targetEntity=Transaction::class, mappedBy="bank")
     */
    private $transactions;

    /**
     * @ORM\Column(type="float")
     */
    private $initialBalance = 0;

    /**
     * @ORM\Column(type="boolean")
     */
    private $status = true;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phoneNumber;

    /**
     * @ORM\ManyToOne(targetEntity=Store::class, inversedBy="banks")
     */
    private $store;

    public function __construct()
    {
        $this->transactions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function getTitle(): ?string
    {
        return $this->getName().'('.$this->getAccountName().')';
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAccountName(): ?string
    {
        return $this->accountName;
    }

    public function setAccountName(string $accountName): self
    {
        $this->accountName = $accountName;

        return $this;
    }

    public function getAccountNumber(): ?string
    {
        return $this->accountNumber;
    }

    public function setAccountNumber(string $accountNumber): self
    {
        $this->accountNumber = $accountNumber;

        return $this;
    }

    public function getBalance(){
        return $this->getInitialBalance() + $this->getAmountCredited() - $this->getAmountDebited();
    }

    public function getAmountCredited(){
        $transactionCredited = array_filter(
            $this->getTransactions()->toArray(), static function(Transaction $transaction){
            return $transaction->getType() === '1';
        });

        return array_sum(array_map(static function(Transaction $transaction){
            return $transaction->getTotalAmount();
        },$transactionCredited ));
    }

    public function getAmountDebited(){
        $transactionDebited = array_filter(
            $this->getTransactions()->toArray(), static function(Transaction $transaction){
            return $transaction->getType() === '0';
        });

        return array_sum(array_map(static function(Transaction $transaction){
            return $transaction->getTotalAmount();
        },$transactionDebited ));
    }

    /**
     * @return Collection|Transaction[]
     */
    public function getTransactions(): Collection
    {
        return $this->transactions;
    }

    public function addTransaction(Transaction $transaction): self
    {
        if (!$this->transactions->contains($transaction)) {
            $this->transactions[] = $transaction;
            $transaction->setBank($this);
        }

        return $this;
    }

    public function removeTransaction(Transaction $transaction): self
    {
        if ($this->transactions->removeElement($transaction)) {
            // set the owning side to null (unless already changed)
            if ($transaction->getBank() === $this) {
                $transaction->setBank(null);
            }
        }

        return $this;
    }

    public function getInitialBalance(): ?float
    {
        return $this->initialBalance;
    }

    public function setInitialBalance(float $initialBalance): self
    {
        $this->initialBalance = $initialBalance;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(?string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    public function getStore(): ?Store
    {
        return $this->store;
    }

    public function setStore(?Store $store): self
    {
        $this->store = $store;

        return $this;
    }
}

src/Form/BankType.php
<?php

namespace App\Form;

use App\Entity\Bank;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BankType extends ApplicationType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name',TextType::class,
                $this->options("form.bank.name.title",
                    'form.bank.name.placeholder'))
            ->add('accountName',
                TextType::class,
                $this->options("form.bank.accountName.title",
                    'form.bank.accountName.placeholder'))
            ->add('accountNumber',
                TextType::class,
                $this->options("form.bank.accountNumber.title",
                    'form.bank.accountNumber.placeholder'),[
                    'required' => false
                ])
            ->add('initialBalance',
                NumberType::class,
                $this->options("form.bank.initialBalance.title",
                    'form.bank.initialBalance.placeholder'))
            ->add('address',
                TextType::class,
                $this->options("form.bank.address.title",
                    'form.bank.address.placeholder'),[
                    'required' => false
                ])
            ->add('phoneNumber',
                TextType::class,
                $this->options("form.bank.phoneNumber.title",
                    'form.bank.phoneNumber.placeholder'),[
                    'required' => false
                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Bank::class,
        ]);
    }
}

src/Controller/BankController.php
<?php


namespace App\Controller;


use App\Entity\Bank;
use App\Entity\Setting;
use App\Entity\Store;
use App\Extension\AppExtension;
use App\Form\BankType;
use App\Repository\BankRepository;
use App\Util\ModuleConstant;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

class BankController extends AbstractController
{
    /**
     * @var AppExtension
     */
    private $appExtension;
    /**
     * @var Setting
     */
    private $setting;

    /**
     * @var Store
     */
    private $store;

    /**
     * BankController constructor.
     * @param AppExtension $appExtension
     * @param RequestStack $requestStack
     */
    public function __construct(AppExtension $appExtension, RequestStack $requestStack)
    {
        $this->appExtension = $appExtension;
        $this->setting = $requestStack->getSession()->get('setting');
        $this->store = $requestStack->getSession()->get('store');
    }


    /**
     * @Route("/bank", name="bank_index")
     * @param BankRepository $bankRepository
     * @return Response
     */
    public function index(BankRepository $bankRepository)
    {
        if (!$this->setting->getWithAccounting() ||
            !$this->appExtension->moduleExists(ModuleConstant::MODULES['acc_man'])){
            throw new NotFoundHttpException("this ressource don't exists");
        }

        $model['banks'] = $bankRepository->findBy(['store' => $this->store]);
        //breadcumb
        $model['entity'] = 'controller.bank.index.entity';
        $model['page'] = 'controller.bank.index.page';
        return $this->render('bank/index.html.twig', $model);
    }

    /**
     * @Route("/bank/updateStatus/{id}", name="bank_update_status")
     * @param Bank $bank
     * @param EntityManagerInterface $entityManager
     * @return RedirectResponse
     */
    public function updateStatus(Bank $bank, EntityManagerInterface $entityManager): RedirectResponse
    {
        if (!$this->setting->getWithAccounting() ||
            !$this->appExtension->moduleExists(ModuleConstant::MODULES['acc_man'])){
            throw new NotFoundHttpException("this ressource don't exists");
        }

        $bank->setStatus(!$bank->getStatus());
        $entityManager->persist($bank);
        $entityManager->flush();

        $this->addFlash('success',"controller.bank.edit.flash.success");
        return $this->redirectToRoute('bank_index');
    }

    /**
     * @Route("/bank/new", name="bank_new")
     * @param Request $request
     * @param EntityManagerInterface $entityManager
     * @return Response
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        if (!$this->setting->getWithAccounting() ||
            !$this->appExtension->moduleExists(ModuleConstant::MODULES['acc_man'])){
            throw new NotFoundHttpException("this ressource don't exists");
        }

        $bank = new Bank();
        $form = $this->createForm(BankType::class,$bank);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $bank->setStore($this->store);
            $entityManager->persist($bank);
            $entityManager->flush();
            $this->addFlash('success',"controller.bank.new.flash.success");
        }

        $model['form'] = $form->createView();
        //breadcumb
        $model['entity'] = 'controller.bank.new.entity';
        $model['page'] = 'controller.bank.new.page';
        return $this->render('bank/new.html.twig',$model);
    }


    /**
     * @Route("/bank/edit/{id}", name="bank_edit")
     * @param Bank $bank
     * @param Request $request
     * @param EntityManagerInterface $entityManager
     * @return Response
     */
    public function edit(Bank $bank, Request $request, EntityManagerInterface $entityManager): Response
    {
        if (!$this->setting->getWithAccounting() ||
            !$this->appExtension->moduleExists(ModuleConstant::MODULES['acc_man'])){
            throw new NotFoundHttpException("this ressource don't exists");
        }

        $form = $this->createForm(BankType::class,$bank);

        if ($request->isMethod('POST')){
            $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid()){
                $entityManager->persist($bank);
                $entityManager->flush();

                $this->addFlash('success',"controller.bank.edit.flash.success");

                return $this->redirectToRoute('bank_index');
            }
        }

        $model['form'] = $form->createView();
        //breadcumb
        $model['entity'] = 'controller.bank.edit.entity';
        $model['page'] = 'controller.bank.edit.page';
        return $this->render('bank/edit.html.twig',$model);
    }

    /**
     * @Route("/bank/delete/{id}", name="bank_delete")
     * @param Bank $bank
     * @param EntityManagerInterface $entityManager
     * @return RedirectResponse
     */
    public function delete(Bank $bank, EntityManagerInterface $entityManager): RedirectResponse
    {
        if (!$this->setting->getWithAccounting() ||
            !$this->appExtension->moduleExists(ModuleConstant::MODULES['acc_man'])){
            throw new NotFoundHttpException("this ressource don't exists");
        }

        $entityManager->remove($bank);
        $entityManager->flush();
        $this->addFlash('success',"controller.bank.delete.flash.success");
        return $this->redirectToRoute('bank_index');
    }


}

templates/bank/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'bank.edit.title'|trans({},'messages',app.session.get('_locale')) }}{% endblock %}

{% block body %}
    <div class="col-md-8 offset-md-2 col-xl-8 offset-xl-2">
        <div class="card">
            <div class="card-body">
                <h5 class="mt-0 header-title">
                    {{ 'bank.edit.block_title'|trans }}
                    <span class="triangle-border-left pull-left"></span>
                    <span class="triangle-border-right pull-right"></span>
                </h5>
                {{ form_start(form) }}
                {{ form_widget(form) }}
                <div class="form-group mt-2">
                    <button class="btn btn-uyblue">
                        <i class="fa fa-edit"></i> &nbsp; {{ 'bank.edit.btn_add'|trans }}
                    </button>
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/bank/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'bank.index.title'|trans({},'messages',app.session.get('_locale')) }}{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('dist/plugins/datatables/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('dist/plugins/datatables/buttons.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('dist/plugins/datatables/responsive.bootstrap4.min.css') }}">
{% endblock %}

{% block javascripts %}
    {%  include 'partials/jsTable.html.twig' %}
    <script src="{{ asset('dist/js/datatable/sb-datatables-'~app.session.get('_locale')~'.js') }}"></script>

    <script type="text/javascript">
        getDataTable($('#dataTable'));
        $('#dataTable tbody').on( 'click', 'tr', function () {
            $(this).toggleClass('selected bg-light');
        } );
    </script>
{% endblock %}
{% block body %}
    <div class="card">
        <div class="card-body">
            <h5 class="mt-0 header-title">
                {{ 'bank.index.block_title'|trans }} ({{ banks|length|formatedInt }})
                <span class="triangle-border-left pull-left"></span>
                <span class="triangle-border-right pull-right ml-3"></span>
                {% if is_granted(permission_verify,'BANK_NEW') %}
                    <span class="pull-right">
                        <a class="btn btn-outline-uyblue" href="{{ path('bank_new') }}">
                            <i class="fa fa-plus"></i>
                        </a>
                    </span>
                {% endif %}
            </h5>
            <div class="table-responsive">
                <table class="table" style="width: 100%;" id="dataTable">
                <thead>
                <tr>
                    <th>{{ 'bank.index.tr_name'|trans }}</th>
                    <th class="not-sort">{{ 'bank.index.tr_accountName'|trans }}</th>
                    <th class="not-sort">{{ 'bank.index.tr_address'|trans }}</th>
                    <th class="not-export not-sort">{{ 'bank.index.tr_initialBalance'|trans }}</th>
                    <th class="not-export not-sort">{{ 'bank.index.tr_balance'|trans }}</th>
                    <th class="not-export not-sort">{{ 'bank.index.tr_status'|trans }}</th>
                    <th class="not-export not-sort"></th>
                </tr>
                </thead>
                <tbody>
                {% for bank in banks %}
                    <tr>
                        <td class="text-capitalize">
                            {{ bank.name }}
                        </td>
                        <td>{{ bank.accountName }}</td>
                        <td>{{ bank.address }} ({{ bank.phoneNumber }})</td>
                        <td>{{ bank.initialBalance|formated }}</td>
                        <td>
                            <a class="{% if bank.balance > 0 %}text-uyblue-dark{% else %}text-danger{% endif %} font-weight-bold" href="{{ path('transaction_index',{bank: bank.id}) }}">
                                {{ bank.balance|formated }}
                            </a>
                        </td>
                        <td>
                            {% if is_granted(permission_verify,'BANK_UPDATE_STATUS') %}
                                {% if bank.status  %}
                                    <a href="{{ path('bank_update_status',{id: bank.id}) }}" class="badge badge-success">
                                        <i class="ti-check"></i> {{ 'bank.index.tr_active'|trans }}
                                    </a>
                                {% else %}
                                    <a href="{{ path('bank_update_status',{id: bank.id}) }}" class="badge badge-danger">
                                        <i class="ti-close"></i> {{ 'bank.index.tr_inactive'|trans }}
                                    </a>
                                {% endif %}
                            {% endif %}
                        </td>
                        <td>
                            {% if is_granted(permission_verify,'BANK_EDIT') %}
                            <a href="{{ path('bank_edit',{'id': bank.id}) }}" class="p-2 badge badge-uyblue">
                                <i class="fa fa-pencil"></i>
                            </a>
                            {% endif %}
                            {% if bank.transactions|length == 0 and is_granted(permission_verify,'BANK_DELETE') %}
                            <a href="#deleteModal{{bank.id}}" data-toggle="modal" class="p-2 badge badge-danger ">
                                <i class="fa fa-remove"></i>
                            </a>
                            <!-- Delete Modal -->
                            <div class="modal fade" id="deleteModal{{bank.id}}" tabindex="-1" role="dialog"
                                 aria-labelledby="deleteModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">{{ 'bank.index.modal.title'|trans }}</h5>
                                            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">×</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            {{ 'bank.index.modal.body'|trans }}
                                            <span class="text-info">{{ bank.title }}</span>?
                                        </div>
                                        <div class="modal-footer">
                                            <button class="btn btn-secondary" type="button" data-dismiss="modal">
                                                {{ 'cancel'|trans }}
                                            </button>
                                            <a class="btn btn-danger" href="{{path('bank_delete',{'id':bank.id})}}">
                                                <i class="fa fa-trash"></i> {{ 'delete'|trans }}
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/bank/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'bank.new.title'|trans({},'messages',app.session.get('_locale')) }}{% endblock %}

{% block body %}
    <div class="col-md-8 offset-md-2 col-xl-8 offset-xl-2">
        <div class="card">
            <div class="card-body">
                <h5 class="mt-0 header-title">
                    {{ 'bank.new.block_title'|trans }}
                    <span class="triangle-border-left pull-left"></span>
                    <span class="triangle-border-right pull-right"></span>
                </h5>
                {{ form_start(form) }}
                {{ form_widget(form) }}
                <div class="form-group mt-2">
                    <button class="btn btn-uyblue">
                        <i class="fa fa-save"></i> &nbsp; {{ 'bank.new.btn_add'|trans }}
                    </button>
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}